In [3]:
import numpy as np

In [8]:
np.random.normal(loc=10, scale=10, size=100)

array([ 19.14672541,  19.105166  ,  13.5883443 ,  -1.46355508,
       -11.99382961,   8.40481028,   8.66824817,   0.70705146,
        19.65039729,  13.44011086,   6.53780458,  10.51854871,
        28.28555391,  15.87784724,  10.01182003,  20.97820655,
        12.48866344,  -2.84295421,  17.20722608,   4.72496095,
        18.32659451,  10.19815915,  12.34608522,  17.68949673,
        29.06824936,  10.60841351,  16.8475263 ,  17.32514983,
        -3.24487827,  11.47028538,  12.23183898,  12.55517703,
        -8.55794667,  17.89644303,  23.10472013,   6.03025713,
         9.80467367,  -2.85287881,  28.04857861,  16.12171601,
        14.00498077,   3.004257  ,  -5.26474941,  17.84325637,
        -0.99279742,   4.25108859,   2.15952239,  24.37053494,
         2.55666767,  18.55909529,  -2.41794323, -16.64729605,
        16.03145764,   6.1790005 ,  14.25387188,  12.96559379,
        13.9467469 ,  18.01388788,   3.93441532,  26.91160524,
         4.00898768,  16.94034118,   6.2470865 ,  11.52

In [7]:
np.random.binomial(n=10, p=0.5, size=100)

array([4, 7, 6, 3, 6, 2, 3, 5, 4, 6, 6, 5, 6, 6, 5, 4, 6, 8, 4, 5, 7, 6,
       6, 3, 4, 6, 6, 2, 6, 2, 5, 6, 5, 6, 5, 4, 7, 5, 4, 6, 6, 4, 3, 7,
       6, 4, 7, 4, 3, 4, 5, 5, 4, 6, 5, 4, 2, 5, 4, 5, 4, 4, 5, 3, 7, 5,
       4, 6, 6, 3, 6, 6, 3, 4, 4, 5, 5, 3, 5, 5, 7, 5, 5, 3, 6, 4, 3, 5,
       6, 6, 6, 7, 6, 3, 5, 3, 4, 5, 7, 5])

In [9]:
np.random.multinomial(n=100, pvals=[0.4,0.3,0.2,0.1])

array([39, 30, 23,  8])

In [10]:
np.random.uniform(low=0, high=1, size=100)

array([0.81244157, 0.66714831, 0.94147745, 0.12402983, 0.04181156,
       0.61584191, 0.50058266, 0.96735869, 0.4683595 , 0.19367663,
       0.32199073, 0.16838849, 0.28553241, 0.1319259 , 0.84467273,
       0.26761448, 0.68765478, 0.34725691, 0.13921052, 0.99201355,
       0.9827001 , 0.48546414, 0.53915378, 0.99237373, 0.84893837,
       0.85538342, 0.82441061, 0.00587739, 0.16157053, 0.45939588,
       0.84748668, 0.33211574, 0.59329837, 0.80460228, 0.18932574,
       0.84947298, 0.19416194, 0.04610718, 0.9969083 , 0.89760147,
       0.67607981, 0.24764222, 0.81663335, 0.23447651, 0.51681181,
       0.60460187, 0.67363822, 0.06992456, 0.80560263, 0.24221697,
       0.44898922, 0.50120367, 0.08745524, 0.34866349, 0.25378064,
       0.94193713, 0.34049569, 0.53188211, 0.32093689, 0.39263229,
       0.45172061, 0.15111401, 0.87057133, 0.81262694, 0.53449786,
       0.25212693, 0.29337531, 0.51187944, 0.23031094, 0.15680721,
       0.60471047, 0.40310448, 0.01875643, 0.99034794, 0.98056

In [11]:
np.random.poisson(lam=20, size=100)

array([14, 24, 23, 16, 23, 18, 22, 20, 26, 26,  9, 22, 18, 27, 17, 13, 22,
       23, 13, 17, 22, 15, 24, 14, 16, 17, 23, 26, 11, 22, 20, 18, 14, 24,
       20, 18, 15, 21, 17, 22, 18, 18, 16, 22, 17, 15, 21, 27, 18, 16, 23,
       20, 21, 19, 19, 14, 17, 21, 21, 17, 17, 20, 17, 16, 17, 25, 26, 18,
       24, 22, 18, 21, 18, 17, 17, 21, 17,  9, 24, 24, 18, 20, 15, 16, 12,
       19, 26, 17, 24, 25, 14, 22, 17, 24, 28, 21, 21, 21, 17, 22])

In [1]:
import numpy as np

temperatures = np.random.uniform(low=25, high=40, size=100)
print(temperatures)

[39.28594669 26.14382466 28.95072252 30.63411127 35.27483845 33.10925363
 33.9490606  25.90199309 31.37989498 29.14446117 32.35793705 29.17818465
 35.92236495 31.20413559 25.65745357 35.14303041 26.50129107 34.80408225
 39.27462235 32.67895326 28.39850654 33.68791979 34.66856393 31.25254012
 35.39951872 37.49893772 28.67841185 37.08602204 35.29975356 31.07690205
 28.49166133 25.6021588  36.34889174 35.95703091 31.98735309 35.64610613
 32.17836666 37.40537608 39.21369265 32.25040501 26.01044868 31.96542668
 32.89960585 27.90945344 37.21435859 30.45585899 32.75438591 30.39833264
 31.41067337 35.60609591 26.13771074 32.71918933 37.46590208 28.20709366
 38.92674476 29.08311054 30.28447378 33.34841997 31.13870873 28.51401049
 36.86491693 33.74295187 37.25467174 32.12055509 32.57124982 28.05339902
 32.27677378 39.72277553 28.57035243 39.74692058 32.87115354 31.67443195
 34.16718178 38.43037558 28.79691122 39.43194168 32.96879303 37.91653617
 35.90636936 25.30331565 30.6732839  26.44559367 26

In [ ]:
marks = np.random.normal(loc=60, scale=10, size=50)
print(marks)


In [2]:
coin_toss = np.random.binomial(n=1, p=0.5, size=100)
print(coin_toss)

[1 0 0 0 1 0 1 0 0 0 1 1 1 0 0 0 1 1 1 0 0 0 1 1 0 0 1 0 1 0 1 1 0 1 0 1 0
 0 1 1 0 1 1 1 0 0 1 1 1 1 0 0 0 1 0 1 1 0 1 0 1 0 0 0 1 0 0 1 0 0 1 1 1 1
 1 0 1 1 1 0 1 1 1 0 0 1 0 0 0 0 1 0 0 1 0 0 0 1 0 1]


In [3]:
salaries = np.random.normal(loc=50000, scale=8000, size=100)

print("Mean:", np.mean(salaries))
print("Max:", np.max(salaries))
print("Sum:", np.sum(salaries))

Mean: 50806.19534948481
Max: 70734.23466591637
Sum: 5080619.534948481


In [4]:
visitors = np.random.poisson(lam=500, size=365)

print("Average Visitors:", np.mean(visitors))
print("Peak Day Visitors:", np.max(visitors))

Average Visitors: 496.9917808219178
Peak Day Visitors: 562


In [5]:
import numpy as np

days = 30

# 1️⃣ Daily Customers (Poisson)
daily_customers = np.random.poisson(lam=200, size=days)

# 2️⃣ Purchase Amount (Normal)
purchase_amount = np.random.normal(loc=1500, scale=300, size=days)

# 3️⃣ Product Category Selection (Multinomial)
product_categories = np.random.multinomial(
    n=200,
    pvals=[0.3, 0.3, 0.2, 0.2],
    size=days
)

# 4️⃣ Delivery Time (Poisson)
delivery_time = np.random.poisson(lam=3, size=days)

# 5️⃣ Waiting Time Between Orders (Exponential)
waiting_time = np.random.exponential(scale=1/10, size=days)

# 6️⃣ Product Quality (Binomial)
product_quality = np.random.binomial(n=1, p=0.9, size=days)

print("Daily Customers:", daily_customers)
print("Purchase Amount:", purchase_amount)
print("Product Categories (A,B,C,D):", product_categories)
print("Delivery Time:", delivery_time)
print("Waiting Time:", waiting_time)
print("Product Quality:", product_quality)

Daily Customers: [179 203 223 178 195 197 230 201 203 195 182 203 229 227 197 209 185 197
 205 223 205 223 207 205 217 197 188 198 205 201]
Purchase Amount: [1835.79452826 1242.05298162 1427.83557754 1750.69791423 1544.72002686
 1817.08743486 1203.44401722 1992.77024915 1996.34802543 1119.04894499
 1240.66676    1951.51115131 1460.88298947  898.14749799 1710.76427358
 1684.11828446 1730.62770769 1361.20410102  870.82413345 1235.08228381
 1468.33382589 1821.60480274 1901.80032934 1178.18084293 1342.69552555
 1128.38120109 1322.15866114 1831.46123417 1066.15955937 1766.24536533]
Product Categories (A,B,C,D): [[56 60 36 48]
 [67 51 42 40]
 [52 59 40 49]
 [58 57 42 43]
 [56 55 42 47]
 [67 62 42 29]
 [62 58 37 43]
 [66 63 35 36]
 [56 67 34 43]
 [57 77 28 38]
 [72 55 38 35]
 [65 74 29 32]
 [82 49 37 32]
 [59 56 44 41]
 [66 47 46 41]
 [57 59 43 41]
 [57 48 43 52]
 [59 59 37 45]
 [58 65 36 41]
 [71 56 39 34]
 [62 57 52 29]
 [57 58 45 40]
 [61 49 41 49]
 [68 62 30 40]
 [46 58 43 53]
 [53 67 48 