In [1]:
import numpy as np

# Rows → Regions, Columns → Months (Jan, Feb, Mar)
regions = np.array(["North", "South", "East", "West"])

sales = np.array([
    [20000, 25000, 30000],   # North
    [18000, 22000, 27000],   # South
    [25000, 26000, 28000],   # East
    [15000, 20000, 21000]    # West
])

# 1️⃣ Total Sales per Region
total_sales_region = np.sum(sales, axis=1)
print("Total Sales per Region:", total_sales_region)

# 2️⃣ Average Sales per Month
avg_sales_month = np.mean(sales, axis=0)
print("Average Sales per Month:", avg_sales_month)

# 3️⃣ Best Performing Region
best_region_index = np.argmax(total_sales_region)
print("Best Performing Region:", regions[best_region_index])

Total Sales per Region: [75000 67000 79000 56000]
Average Sales per Month: [19500. 23250. 26500.]
Best Performing Region: East


In [2]:
students = np.array(["A", "B", "C", "D"])
marks = np.array([85, 92, 78, 88])

# Sort descending
sorted_indices = np.argsort(marks)[::-1]

print("Student Ranking:")
for i in sorted_indices:
    print(students[i], marks[i])

Student Ranking:
B 92
D 88
A 85
C 78


In [3]:
# 1 = Good, 0 = Defective
quality = np.random.binomial(1, 0.9, 100)

print("Total Produced:", len(quality))
print("Good Products:", np.sum(quality))
print("Defective Products:", len(quality) - np.sum(quality))

Total Produced: 100
Good Products: 91
Defective Products: 9


In [4]:
# Base prices of products
prices = np.array([100, 200, 300])

# Tax percentage
tax = 0.18

# Broadcasting
final_price = prices + prices * tax

print("Final Prices:", final_price)

Final Prices: [118. 236. 354.]


In [5]:
customer_data = np.array([
    [101, 25, 5000, 1],
    [102, 30, 7000, 2],
    [103, 22, 4000, 1],
    [104, 35, 10000, 3],
    [105, 28, 6500, 2]
])

# Columns:
# 0 → customer id
# 1 → age
# 2 → purchase_amount
# 3 → region

# 1️⃣ Total Customers
print("Total Customers:", customer_data.shape[0])

# 2️⃣ Extract Purchase Column
purchase_column = customer_data[:, 2]
print("Purchase Column:", purchase_column)

# 3️⃣ Average Purchase
print("Average Purchase:", np.mean(purchase_column))

# 4️⃣ Max & Min Purchase
print("Maximum Purchase:", np.max(purchase_column))
print("Minimum Purchase:", np.min(purchase_column))

# 5️⃣ Customers Above Average Purchase
above_avg = customer_data[purchase_column > np.mean(purchase_column)]
print("Customers Above Average Purchase:\n", above_avg)


Total Customers: 5
Purchase Column: [ 5000  7000  4000 10000  6500]
Average Purchase: 6500.0
Maximum Purchase: 10000
Minimum Purchase: 4000
Customers Above Average Purchase:
 [[  102    30  7000     2]
 [  104    35 10000     3]]


In [6]:
employee_data = np.array([
    [1, 25, 40000],
    [2, 30, 50000],
    [3, 35, 60000],
    [4, 28, 45000],
    [5, 40, 70000]
])

# Columns:
# 0 → employee id
# 1 → age
# 2 → salary

salary = employee_data[:, 2]
age = employee_data[:, 1]

print("Total Salary:", np.sum(salary))
print("Minimum Salary:", np.min(salary))
print("Maximum Salary:", np.max(salary))
print("Average Age:", np.mean(age))
print("Total Employees:", employee_data.shape[0])

# Correlation between Age & Salary
correlation = np.corrcoef(age, salary)
print("Correlation Matrix:\n", correlation)

Total Salary: 265000
Minimum Salary: 40000
Maximum Salary: 70000
Average Age: 31.6
Total Employees: 5
Correlation Matrix:
 [[1.         0.99938928]
 [0.99938928 1.        ]]
